config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "photos#about_us"

  post "/client_generator", to:"clients#client_generator", as: 'client_generator'

  resources :clients, only:[:create] do 
    resources :consultations, only:[:new, :create]
    resources :reviews, only:[:new, :create]
  end 
  
  resources :photos, only:[:index, :about_us]
 
  resource :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :reviews, only: [:index, :destroy, :update] do 
  #nest the approvals route to reviews
      resource :approvals, only: [:create]
  end 
  
  resources :consultations, only: [:index, :destroy, :update] do 
    resource :approvals, only: [:update]
  end 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :consultations
    has_many :reviews

    #validate for the uniquess of a client validate: uniquness: true
end

app/models/consultation.rb
class Consultation < ApplicationRecord
    belongs_to :client

    scope :not_processed, -> {where(processed: false)}
    scope :processed, -> {where(processed: true)}
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :client 

    scope :not_approved, -> {where(approved: false)}
    scope :approved, -> {where(approved: true)}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # I dont understand this syntax well
    
    helper_method :current_user

    private 
        def current_user
            user_id = session[:user_id]
            # if user_id
            #     return User.find(user_id)
            # else
            #     return nil
            # end
            user_id && User.find(user_id)
        end
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
    #you still need before_action to actually validate even though you have a nested route
    #before_action :require_login, only: [:new]

      def create 
        #update the deafult value for approval to be true
        @review = Review.find(params[:review_id])
        @review.approved = true 

        if @review.save
          redirect_to reviews_url, notice: "Review successfully approved"
        else
          render plain:"Unable to approve the review"
        end 

      end 

      def update
        @consultation = Consultation.find(params[:consultation_id])
        @consultation.processed = true 
        @client = @consultation.client

        if @consultation.save
          ConsultationsMailer.processed_email_mailer(@client).deliver_now
          redirect_to reviews_url
        else 
          render plain: 'Unable to process'
        end 
      end 

    def require_login
        unless  session[:user_id]
          redirect_to new_session_url
        end
    end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    def create

        @client = Client.find_by(email: params[:client][:email])
        if !@client || @client == nil 
            @client = Client.create(email: params[:client][:email])
        end 
            redirect_to new_client_consultation_url(@client)
    end 

    def client_generator

        @client = Client.find_by(email: params[:client][:email])
        if !@client || @client == nil 
            @client = Client.create(email: params[:client][:email])
        end 
        redirect_to  new_client_review_url(@client)
    end 

    
end

app/controllers/consultation_controller.rb
class ConsultationsController < ApplicationController

    def new
        @consultation_request = Consultation.new
    end

    def create
    end

end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController

    def new
        @client = Client.find(params[:client_id])
        @consultation = Consultation.new
    end

    def create
        @client = Client.find(params[:client_id])
        @consultation = Consultation.new(consultation_params)
        @consultation.client = @client
        if @client.update(client_params) && @consultation.save
            
            ConsultationsMailer.consultation_mailer(@client).deliver_now

            redirect_to root_url, notice: "Consultation successfully requested. You will get an email confirmatiion momentarily"
           
            else
            render plain: "We have not been able to process your consultation request"
            
            end 
    end
    
    
    private 
    def consultation_params 
        params.require(:consultation).permit(:request)
    end 

    def client_params 
        params.require(:client).permit(:first_name, :last_name, :email, :phone)
    end 

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    #gems for photo uploads from my wife for the gallery page: active_storage(rails option), https://medium.com/@anaharris/how-to-add-image-upload-functionality-to-your-rails-app-9f7fc3f3d042

    def index
    end 

    def about_us
    end 
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    #before_action :require_login, only: [:destroy]
    def index
       @approved_reviews = Review.approved
       @awaiting_approval = Review.not_approved
       @not_approved_consultations = Consultation.not_processed
       @approved_consultations = Consultation.processed
       
    end 

    def new
        @client = Client.find(params[:client_id])
        @review = Review.new
    end 
        
    def create
            @client = Client.find(params[:client_id])
            @review = Review.new(review_params)

            #look into strong params (also on ruby on rails guide)
            
            @review.client = @client

                if @client.update(client_params) && @review.save
                    redirect_to reviews_url, notice: "Thank you for your review"
                else

                render plain: "We have not been able to process your review. Please try again later."
                
                end  
    end 

    def update 

    end 

    def destroy
        @review = Review.find_by(params[:id])
        @review.delete

    end 

    private

    def review_params 
        params.require(:review).permit(:review)
    end 

    def client_params 
        params.require(:client).permit(:first_name, :last_name, :email, :phone)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end 

    def create
        submitted_email = params[:session][:email]
        submitted_password = params[:session][:password]
        @user = User.find_by(email: submitted_email)

        if @user && @user.authenticate(submitted_password)
            #create a session 
            session[:user_id] = @user.id
            redirect_to reviews_url
        else
            render :new
        end 
    end 

    def destroy
        #finish a session 
        session[:user_id] = nil
        redirect_to root_url
    end 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end 

    def create
        @user = User.new
        submitted_email = params[:user][:email]
        submitted_password = params[:user][:password]
        submitted_password_confirmation = params[:user][:password_confirmation]
        @user.email = submitted_email
        #the password column has to just be named password (not password digest)
        @user.password = submitted_password
        @user.save

        if @user.save 
            redirect_to new_session_path
        else
            render plain: "You have not been able to succwfully create a user"
        end 
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/consultation_helper.rb
module ConsultationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/photos/about_us.html.erb
<div> 
  <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <h3 class = "mission_statement_title"> Our Mission Statement </h2> 

  <h5 class = "mission_statement"> 
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  </h5>

  <h5 class = "qualifications_statement"> 
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  </h5>
</div>

app/views/photos/index.html.erb
<h1 class = 'welcome_gallery_statement'> Gallery </h1> 

    <h3 style = "text-align: center;"> Baby Hair </h3> 
<div class = "set_of_pictures "> 
    <div class="card column" style="width: 18rem;">
        <%= image_tag('baby_hair_before.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
    <div class = "column" > 
        <h6>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus malesuada ornare. In aliquam eu purus ut scelerisque. Cras volutpat et mauris at pretium. Suspendisse finibus mattis mauris non pretium. Nulla ligula magna, blandit dictum nisl at, interdum sodales ante. Donec vitae diam mauris. Sed sodales tortor non ligula semper dictum. Donec non elit tincidunt, mollis lectus id, porttitor felis. Donec maximus dapibus nisl, quis hendrerit nunc sollicitudin non. In luctus malesuada nibh quis tristique.</h6>
    </div>
    <div class="card column " style="width: 18rem;">
        <%= image_tag('baby_hair_after.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
</div>

<h3 style = "text-align: center;"> Bald Spots </h3> 
<div class = "set_of_pictures "> 
    <div class="card column " style="width: 18rem;">
        <%= image_tag('bald_spot_before.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
    <div class = "column" > 
        <h6>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus malesuada ornare. In aliquam eu purus ut scelerisque. Cras volutpat et mauris at pretium. Suspendisse finibus mattis mauris non pretium. Nulla ligula magna, blandit dictum nisl at, interdum sodales ante. Donec vitae diam mauris. Sed sodales tortor non ligula semper dictum. Donec non elit tincidunt, mollis lectus id, porttitor felis. Donec maximus dapibus nisl, quis hendrerit nunc sollicitudin non. In luctus malesuada nibh quis tristique.</h6>
    </div>
    <div class="card column" style="width: 18rem;">
        <%= image_tag('bald_spot_after.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
</div>

<h3 style = "text-align: center;"> Adding Grey Hairs For More Natural Look </h3> 
<div class = "set_of_pictures "> 
    <div class="card column" style="width: 18rem;">
        <%= image_tag('add_grey_hair_before.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
    <div class = "column" > 
        <h6>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus malesuada ornare. In aliquam eu purus ut scelerisque. Cras volutpat et mauris at pretium. Suspendisse finibus mattis mauris non pretium. Nulla ligula magna, blandit dictum nisl at, interdum sodales ante. Donec vitae diam mauris. Sed sodales tortor non ligula semper dictum. Donec non elit tincidunt, mollis lectus id, porttitor felis. Donec maximus dapibus nisl, quis hendrerit nunc sollicitudin non. In luctus malesuada nibh quis tristique.</h6>
    </div>
    <div class="card column" style="width: 18rem;">
        <%= image_tag('add_grey_hair_after.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
</div>

<h3 style = "text-align: center;"> Adding Length To The Bottom Of The Wig </h3> 
<div class = "set_of_pictures "> 
    <div class="card column" style="width: 18rem;">
        <%= image_tag('adding_length_to_bottom_before.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
    <div class = "column" > 
        <h6>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus malesuada ornare. In aliquam eu purus ut scelerisque. Cras volutpat et mauris at pretium. Suspendisse finibus mattis mauris non pretium. Nulla ligula magna, blandit dictum nisl at, interdum sodales ante. Donec vitae diam mauris. Sed sodales tortor non ligula semper dictum. Donec non elit tincidunt, mollis lectus id, porttitor felis. Donec maximus dapibus nisl, quis hendrerit nunc sollicitudin non. In luctus malesuada nibh quis tristique.</h6>
    </div>
    <div class="card column" style="width: 18rem;">
        <%= image_tag('adding_length_to_bottom_after.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
</div>

<h3 style = "text-align: center;"> Bang Replacement </h3> 
<div class = "set_of_pictures "> 
    <div class="card column" style="width: 18rem;">
        <%= image_tag('bang_replacement_before.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
    <div class = "column" > 
        <h6>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus malesuada ornare. In aliquam eu purus ut scelerisque. Cras volutpat et mauris at pretium. Suspendisse finibus mattis mauris non pretium. Nulla ligula magna, blandit dictum nisl at, interdum sodales ante. Donec vitae diam mauris. Sed sodales tortor non ligula semper dictum. Donec non elit tincidunt, mollis lectus id, porttitor felis. Donec maximus dapibus nisl, quis hendrerit nunc sollicitudin non. In luctus malesuada nibh quis tristique.</h6>
    </div>
    <div class="card column" style="width: 18rem;">
        <%= image_tag('bang_replacement_after.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
</div>

<h3 style = "text-align: center;"> Skin Top Flattening </h3> 
<div class = "set_of_pictures "> 
    <div class="card column" style="width: 18rem;">
        <%= image_tag('skin_top_flattening_before.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
    <div class = "column" > 
        <h6>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus faucibus malesuada ornare. In aliquam eu purus ut scelerisque. Cras volutpat et mauris at pretium. Suspendisse finibus mattis mauris non pretium. Nulla ligula magna, blandit dictum nisl at, interdum sodales ante. Donec vitae diam mauris. Sed sodales tortor non ligula semper dictum. Donec non elit tincidunt, mollis lectus id, porttitor felis. Donec maximus dapibus nisl, quis hendrerit nunc sollicitudin non. In luctus malesuada nibh quis tristique.</h6>
    </div>
    <div class="card column" style="width: 18rem;">
        <%= image_tag('skin_top_flattening_after.jpeg', :class=> "card-img-top")  %> 
    <div class="card-body">
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    </div>
</div>

app/views/reviews/index.html.erb
<% if current_user %> 
        <% flash.each do |type, msg| %>
            <div>
            <%= msg %>
            </div>
        <% end %>

     <h1> These are the reviews that await your approval and confirmation </h1> 

        <% @awaiting_approval.each do |review| %> 

          
            <h2> Submitted by <%= review.client.first_name %> <%= review.client.last_name %> </h2> 
            <h3> In the review <%= review.client.first_name %> <%= review.client.last_name %> writes that <%= review.review %> </h3> 
     
         
        
            <div>
                    <%= form_for review, url:  review_approvals_path(review), method: :post do |f| %>
                        <%= f.submit "Approve review" %> 
                    <% end %> 
            </div>
        
            <div> 
                 <%= link_to "Delete review", review_path(review), method: :delete, data: {confirm: "Are you you would like to delete this review?" } %>
            </div>       
        <%  end %>  
        

        <h1> These are the consultations that still need to be processes </h1> 

        <%  @not_approved_consultations.each do |consultation| %> 

          
            <h2> Submitted by <%= consultation.client.first_name %> <%= consultation.client.last_name %> </h2> 
            <h3> In the review <%= consultation.client.first_name %> <%= consultation.client.last_name %> writes that <%= consultation.request %> </h3> 
     
         
        
            <div>
                    <%= form_for consultation, url:  consultation_approvals_path(consultation), method: :put do |f| %>

                        <%= f.submit "Process consultation" %> 
                    <% end %> 
            </div>
        
            <div> 
                 <%= link_to "Delete consultation", consultation_path(consultation), method: :delete, data: {confirm: "Are you you would like to delete this consultation?" } %>
            </div> 
        <% end %>





   
            <% else %> 

   <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>

  
   <% if @approved_reviews.count > 0 %>


     <h3 class = 'reviews_title'> Reviews </h3> 

        <% @approved_reviews.each do |review| %> 

        <div class = ' shadow-lg p-3 mb-5 rounded review_item'> 
            <h4 > "<%= review.review %>" </h4> 
            <br> <br> 
            <h6 class = 'client_name'> <%= review.client.first_name %> <%= review.client.last_name %> </h6> 
        </div> 

        <%  end %> 
        
        <%= form_for :client, url: client_generator_path do |f| %> 

            <div > 
               <%= f.label :email %>
               <%= f.text_field :email %>
           </div>
           
        <%= f.submit "Submit Review"  %>
    
        <% end %> 

   <% else %> 
   <p>  no reviews yet  </p>

        <%= form_for :client, url: client_generator_path do |f| %> 

            <div > 
            <%= f.label :email %>
            <%= f.text_field :email %>
            </div>
        
        <%= f.submit "Submit Review"  %>

   <% end %> 

   <% end %> 
   <% end %>
   

app/views/reviews/new.html.erb
<h1> Submiit a review </h1> 
<h2> Please fill out the form and submit your review. We greatly appreciate all reviews</h2> 

<%= form_for [@client, @review] do |f| %>

    <%= fields_for @client do |ff| %> 
        

        <div> 
            <%= ff.label :first_name %>
            <%= ff.text_field :first_name %>
        </div> 
    
        <div> 
        
            <%= ff.label :last_name %>
            <%= ff.text_field :last_name %>
       
        </div> 

        <div> 
       
            <%= ff.label :email %>
            <%= ff.text_field :email %>
       
        </div> 

        <div> 
      
            <%= ff.label :phone %>
            <%= ff.number_field :phone %> 
        
        </div> 

     <% end %> 

        <div> 
            <%= f.label :review %>
            <%= f.check_box :review %> 
        </div> 

        <div> 
            <%= f.label :review %>
            <%= f.text_field :review %> 
        </div> 

<%= f.submit "Submit review" %>

<% end %>

<%= link_to "Home page", photos_path %> 

<%= link_to "Admin Login", new_session_path %> 